### ISSUE TITLE
getFlutterEngine(): FlutterEngine' is deprecated. Deprecated in Java

### ISSUE THREAD

**Issue by Kasre96** [hifiaz/country-list-pick#1]
Hello @hifiaz 
I was recently building my project and it returned a warning: `getFlutterEngine(): FlutterEngine' is deprecated. Deprecated in Java`

I'm afraid it might lead o breakages in future builds. 

If there's anything that can be done.

Thanks

**Comment by hifiaz** [comment]
@Kasre96 are you using a plugin shared_preferences? try to update to new version

**Comment by Kasre96** [comment]
@hifiaz  yes. Let me.

**Comment by hifiaz** [comment]
@Kasre96 i think the problem in shared_preferences tell me if this issue has solved
