### ISSUE TITLE
Invalid plugin specification country_list_pick.

### ISSUE THREAD

**Issue by felixagbavor** [hifiaz/country-list-pick#14]
flutter pub get results in the following error after adding the plugin. 

Invalid plugin specification country_list_pick.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here:
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by hifiaz** [comment]
thank @felixagbavor for this report

updated for 1.0.0+5
[Commit](https://github.com/hifiaz/country-list-pick/commit/862026acb7e62f050f1bcfcfc2e02e6cd4a867e6)
