### ISSUE TITLE
Accessibility warning for search button

### ISSUE THREAD

**Issue by tomrozb** [hifiaz/country-list-pick#2]
First of all great library! Thanks for your hard work.

Would you consider improving accessibility for the country list? There's a warning for e.g. search button (top right corner).

> This item may not have a label readable by screen readers.

Also the check button displays below the alphabet letters. Looks like it can also be improved.

![22](https://user-images.githubusercontent.com/4646706/82043609-2ce57d00-96ac-11ea-9b6c-3db58f95337e.png)

**Comment by hifiaz** [comment]
@tomrozb Thank you for the advice, I will fix it as best I can

**Comment by hifiaz** [comment]
hi @tomrozb thanks for you suggestion, updated in 1.0.0+3
