### ISSUE TITLE
How do I set the default country to the United States? Now initialSelection='+1', which displays the Canadian

### ISSUE THREAD

**Issue by 978740431** [hifiaz/country-list-pick#29]
How do I set the default country to the United States? Now initialSelection='+1', which displays the Canadian

country_list_pick: ^1.0.1+2
Flutter (Channel stable, 1.22.4

![image](https://user-images.githubusercontent.com/11803404/100237143-7a9b4600-2f69-11eb-8fee-88ee2b513575.png)

**Comment by PlutoHDDev** [comment]
Hello, what is your solution for this problem? I have the same question.

**Comment by netojose** [comment]
Use **US** instead
