### ISSUE TITLE
Add the possibility to hide the country code

### ISSUE THREAD

**Issue by dev-fema** [hifiaz/country-list-pick#3]
Is it possible to add a new selector `isShownCode ` to hide the country?
So that the default aspect of the picker can only be the flag.

**Comment by hifiaz** [comment]
@dev-fema if you mean only show flag, you can set isShowTitle:false

**Comment by dev-fema** [comment]
@hifiaz no i'm referring to the country code (telephone prefix).  If you set the widget as follows:
```
isShowFlag: true,
isShowTitle: false,
isDownIcon: true,
```
the result is "[flag] +39 [arrow icon]".
The option i'm mentioning will be able to get rid of the "+39" part.

**Comment by hifiaz** [comment]
hi @dev-fema  thanks for you suggestion, updated in 1.0.0+3
