### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Mun0nKado** [hifiaz/country-list-pick#37]
If you want to not hardcode the alphabet list

List _alphabet = List.generate(26, (i) => String.fromCharCode('A'.codeUnitAt(0) + i)))

https://github.com/hifiaz/country-list-pick/blob/0dc7f81e86c39178ded26c072ca6145bd1f6d71e/lib/selection_list.dart#L61

**Comment by hifiaz** [comment]
Thank you @Mun0nKado updated in 1.0.1+4
