### ISSUE TITLE
unable to locate flags

### ISSUE THREAD

**Issue by digitpk** [hifiaz/country-list-pick#7]
════════ Exception caught by image resource service ════════════════════════════════════════════════
Unable to load asset: packages/country_list_pick/flags/af.png
════════════════════════════════════════════════════════════════════════════════════════════════════

<<<< [   +4 ms] Error while trying to load an asset: Failed to load asset at "assets/packages/country_list_pick/flags/cu.png" (404) >>>>

**Comment by hifiaz** [comment]
@digitpk please do flutter clean
